[package]
name = "dal"
version = "0.1.0"
edition = "2024"

[dependencies]
clickhouse = "0.12"
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
