[package]
name = "actix_webapi"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4"
log4rs = "1.3"

