appenders:
  my_stdout:
    kind: console # log to consol
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  my_file_logger:
    kind: file #log to file under folder /log
    path: "log/app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}" #date format UTC
root:
  level: trace
  appenders:
    - my_stdout
    - my_file_logger
