[package]
name = "dao"
version = "0.1.0"
edition = "2024"

[dependencies]
clickhouse = { version = "0.12", features = ["time", "uuid"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
